export const cars = [
  {
    id: '1',
    name: 'Mini Cooper 2020',
    imgSrc: '/mini-cooper.png',
    nextReservation: '10/07',
    status: 'Available',
    rating: 2,
  },
  {
    id: '2',
    name: 'Celta 2000',
    imgSrc: '/celta-2000.png',
    nextReservation: '06/07',
    status: 'Available',
    rating: 3,
  },
  {
    id: '3',
    name: 'Fiat 147',
    imgSrc: '/fiat-147.png',
    nextReservation: '02/03',
    status: 'Unavailable',
    rating: 2,
  },
  {
    id: '4',
    name: 'Marea Turbo 2007',
    imgSrc: '/marea-turbo.png',
    nextReservation: '05/03',
    status: 'Unavailable',
    rating: 5,
  },
  {
    id: '5',
    name: 'Opala Turbo 1978',
    imgSrc: '/opala-1978-turbo.png',
    nextReservation: '10/07',
    status: 'Available',
    rating: 3,
  },
  {
    id: '6',
    name: 'Fiat Uno 2013',
    imgSrc: '/fiat-uno.png',
    nextReservation: '02/03',
    status: 'Unavailable',
    rating: 4,
  },
]
